/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat8
 * Generated at: 2017-12-12 06:44:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.naming.*;
import com.zimbra.cs.taglib.bean.BeanUtils;

public final class secureRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	//
	// Constants
	//

	// TODO: Is this defined somewhere? LocalConfig?
	static final String CONTEXT = "/service";
	static final String PATH = "/soap";

	static final String P_DATA = "data";

	static String httpPort = null;

	static {
		try {
			Context initCtx = new InitialContext();
			Context envCtx = (Context) initCtx.lookup("java:comp/env");
			httpPort = (String)envCtx.lookup("httpPort");
		} 
		catch (NamingException ne) {
			// ignore
		}
	}


	//
	// Classes
	//

	static class WrappedRequest extends HttpServletRequestWrapper {
		// Data
		String data;
		// Constructors
		public WrappedRequest(HttpServletRequest request) {
			super(request);
			data = request.getParameter(P_DATA);
//			data =
//				"<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\">"+
//					"<soap:Header>"+
//						"<context xmlns=\"urn:zimbra\">"+
//							"<userAgent xmlns=\"\" name=\"ZimbraWebClient - FF3.0 (Mac)\" version=\"0.0\"/>"+
//							"<sessionId xmlns=\"\" id=\"113\"/>"+
//							"<account xmlns=\"\" by=\"name\">user1@localhost</account>"+
//							"<format xmlns=\"\" type=\"js\"/>"+
//							"<authToken xmlns=\"\">"+
//								"0_1e28187778023ad967b28c08038f00e7931d7eff_69643d33363a66643764306462372d636331302d3463303" +
//								"62d393833652d6630386135313331383336373b6578703d31333a313232363031353939303436303b747970653d363a7a696d6272613b" +
//							"</authToken>"+
//						"</context>"+
//					"</soap:Header>"+
//					"<soap:Body>"+
//						"<NoOpRequest xmlns=\"urn:zimbraMail\"/>" +
//					"</soap:Body>" +
//				"</soap:Envelope>"
//			;
		}
		// paths
		public StringBuffer getRequestURL() { return new StringBuffer(CONTEXT+PATH); }
		public String getRequestURI() { return CONTEXT+PATH; }
		public String getServletPath() { return CONTEXT; }
		// parameters
		// NOTE: For some completely *unknown* reason, I am not able to
		//       override any methods related to parameters. If I compile
		//       the resulting .java file from the command-line it works
		//       fine; inside of Jetty, it barfs and dies. Why?!?!
		/***
		public Enumeration getParameterNames() {
			List nameList = new LinkedList();
			Enumeration names = super.getParameterNames();
			while (names.hasMoreElements()) {
				nameList.add(names.nextElement());
			}
			return Collections.enumeration(nameList);
		}
		public String getParameter(String name) {
			return name.equals(P_DATA) ? null : super.getParameter(name);
		}
		public Map getParameterMap() {
			Map<String,String> map = new HashMap<String,String>(super.getParameterMap());
			map.remove("data");
			return map;
		}
		// TODO: getParameterValues():String[]
		/***/
		// i/o
		public ServletInputStream getInputStream() throws IOException {
			byte[] bytes = this.data.getBytes("UTF-8");
			return new WrappedInputStream(new ByteArrayInputStream(bytes));
		}
		public BufferedReader getReader() {
			return new BufferedReader(new StringReader(this.data));
		}
		// other
		public String getMethod() { return "POST"; }
		public int getContentLength() {
			try {
				return this.data.getBytes("UTF-8").length;
			}
			catch (Exception e) {
				return super.getContentLength();
			}
		}
	}
	static class WrappedResponse extends HttpServletResponseWrapper {
		// Data
		ByteArrayOutputStream bout;
		StringWriter sout;
		String redirectLocation;
		// Constructors
		public WrappedResponse(HttpServletResponse response) {
			super(response);
		}
		// Public methods
		public String getData() {
			try {
				return this.bout != null ? new String(this.bout.toByteArray(), "UTF-8") : this.sout.toString();
			}
			catch (Exception e) {
				return "";
			}
		}
		public String getRedirectLocation() {
			return this.redirectLocation;
		}
		// other
		public void sendRedirect(String location) {
			this.redirectLocation = location;
		}
		// i/o
		public ServletOutputStream getOutputStream() throws IOException {
			if (this.bout == null) this.bout = new ByteArrayOutputStream(1024);
			return new WrappedOutputStream(this.bout);
		}
		public PrintWriter getWriter() {
			if (this.sout == null) this.sout = new StringWriter();
			return new PrintWriter(this.sout);
		}
	}
	static class WrappedInputStream extends ServletInputStream {
		// Data
		InputStream in;
		// Constructors
		public WrappedInputStream(InputStream in) {
			this.in = in;
		}
		// InputStream methods
		public int read() throws IOException {
			return in.read();
		}
		// ServletInputStream methods
		public int readLine(byte[] buffer, int off, int len) throws IOException {
			for (int i = 0; i < len; i++) {
				int b = read();
				if (b == -1) return -1;
				buffer[off + i] = (byte)b;
			}
			return len;
		}
        public boolean isReady() {
            return true;
            //TODO: this isn't right, just stubbed for now so we can build
        }
        public void setReadListener(ReadListener listener) {
            //TODO: this isn't right, just stubbed for now so we can build
        }
        public boolean isFinished() {
            return false;
            //TODO: this isn't right, just stubbed for now so we can build
        }
	}
	static class WrappedOutputStream extends ServletOutputStream {
		// Data
		OutputStream out;
		// Constructors
		public WrappedOutputStream(OutputStream out) {
			this.out = out;
		}
		// OutputStream methods
		public void write(int b) throws IOException {
			this.out.write(b);
		}
		// ServletOutputStream methods
		public void print(boolean b) throws IOException { print(String.valueOf(b)); }
		public void print(char c) throws IOException { print(String.valueOf(c)); }
		public void print(double d) throws IOException { print(String.valueOf(d)); }
		public void print(float f) throws IOException { print(String.valueOf(f)); }
		public void print(int i) throws IOException { print(String.valueOf(i)); }
		public void print(long l) throws IOException { print(String.valueOf(l)); }
		public void print(String s) throws IOException { this.out.write(s.getBytes("UTF-8")); }
		public void println() throws IOException { print("\n"); }
		public void println(boolean b) throws IOException { print(b);println(); }
		public void println(char c) throws IOException { print(c);println(); }
		public void println(double d) throws IOException { print(d);println(); }
		public void println(float f) throws IOException { print(f);println(); }
		public void println(int i) throws IOException { print(i);println(); }
		public void println(long l) throws IOException { print(l);println(); }
		public void println(String s) throws IOException { print(s);println(); }
        public boolean isReady() {
            return true;
            //TODO: this isn't right, just stubbed for now so we can build
        }
        public void setWriteListener(WriteListener listener) {
            //TODO: this isn't right, just stubbed for now so we can build
        }
	}

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("zm:encodeHtmlAttr", com.zimbra.cs.taglib.bean.BeanUtils.class, "encodeHtmlAttr", new Class[] {java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("zm:jsEncode", com.zimbra.cs.taglib.bean.BeanUtils.class, "jsEncode", new Class[] {java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.zimbra.cs.taglib.bean.BeanUtils");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n * ***** BEGIN LICENSE BLOCK *****\n * Zimbra Collaboration Suite Web Client\n * Copyright (C) 2008, 2009, 2010, 2012, 2013, 2014, 2016 Synacor, Inc.\n *\n * This program is free software: you can redistribute it and/or modify it under\n * the terms of the GNU General Public License as published by the Free Software Foundation,\n * version 2 of the License.\n *\n * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;\n * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n * See the GNU General Public License for more details.\n * You should have received a copy of the GNU General Public License along with this program.\n * If not, see <https://www.gnu.org/licenses/>.\n * ***** END LICENSE BLOCK *****\n-->\n");

	// make sure we only get called securely!
	if (!request.getScheme().equals("https")) {
		response.sendError(HttpServletResponse.SC_FORBIDDEN, "Must use https to connect.");
		return;
	}

	// proxy request, capturing output
	WrappedRequest wrappedRequest = new WrappedRequest(request);
	WrappedResponse wrappedResponse = new WrappedResponse(response);

	ServletContext context = getServletContext().getContext(CONTEXT);
	RequestDispatcher dispatcher = context.getRequestDispatcher(PATH);
	dispatcher.include(wrappedRequest, wrappedResponse);

	// information
	String data = wrappedResponse.getData();
	String encodedData = data;
	if (data != null) {
		// TODO: protecting against textarea tag in text is making some assumptions
		encodedData = data.replaceAll("(</[Tt][Ee])([Xx][Tt])","$1\"+\"$2");
	}

	String server = request.getServerName();
	String port = httpPort != null && !httpPort.equals("80") ? ":"+httpPort : "";
	String url = "http://"+server+port+request.getContextPath()+"/public/insecureResponse.jsp";

    String HEADER_X_FRAME_OPTIONS = "X-Frame-Options";
    String X_FRAME_OPTIONS_VALUE = "ALLOWFORTHISFRAME";  // Any random value to override the inherited x-frame-options from the parent.

	pageContext.setAttribute("data", data);
	pageContext.setAttribute("encodedData", encodedData);
	pageContext.setAttribute("server", server);
	pageContext.setAttribute("port", port);
	pageContext.setAttribute("url", url);
	pageContext.setAttribute("millis", System.currentTimeMillis());

	// no cache
    response.setHeader(HEADER_X_FRAME_OPTIONS, X_FRAME_OPTIONS_VALUE);
	response.addHeader("Vary", "User-Agent");
	response.setHeader("Expires", "Tue, 24 Jan 2000 17:46:50 GMT");
	response.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0");
	response.setHeader("Pragma", "no-cache");

	// generate output
	response.setContentType("text/html");

      out.write("<html>\n<body>\n<!-- the form is used if data too long to transmit via request params -->\n<form id=form target=\"iframe-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=POST action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n<input type=hidden name=reqId value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zm:encodeHtmlAttr(param.reqId)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("\">\n<textarea name=data>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${encodedData}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n</form>\n<iframe id=\"iframe-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"iframe-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></iframe>\n<script>\nvar data = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zm:jsEncode(data)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("\";\nvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\nvar params = [\n\t\"?\",\n\t\"reqId=\",encodeURIComponent(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zm:jsEncode(param.reqId)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("\"),\n\t\"&\",\n\t\"data=\",encodeURIComponent(data)\n].join(\"\");\n\n// submit the request\nif (url.length + params.length < 2048) {\n\tdocument.getElementById(\"iframe-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${server}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${millis}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").src = url+params;\n}\nelse {\n\tdocument.getElementById(\"form\").submit();\n}\n</script>\n</body>\n</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
